
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Pregunta;
import com.mycompany.proyecto_u1.models.Respuesta;
import java.util.ArrayList;
import java.awt.Component; // Para iterar componentes
import java.awt.GridLayout; // Para el panel de sub-preguntas
import javax.swing.border.EmptyBorder; // Para el margen
public class ComplejaPreguntaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ComplejaPreguntaPanel
     */
    public ComplejaPreguntaPanel() {
        initComponents();
    }
    
    public ComplejaPreguntaPanel(Pregunta preguntaCompleja) {
    initComponents(); 

    btnToggle.setText(preguntaCompleja.getTexto());
    btnToggle.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    panelSubPreguntas.setLayout(new GridLayout(0, 1, 0, 10));
    panelSubPreguntas.setBorder(new EmptyBorder(10, 0, 10, 10)); 
    panelSubPreguntas.setAlignmentX(Component.LEFT_ALIGNMENT);
    
    for (Pregunta subPregunta : preguntaCompleja.getSubPreguntas()) {
        PreguntaPanel panelSub = new PreguntaPanel(subPregunta);
        panelSubPreguntas.add(panelSub);
    }
    panelSubPreguntas.setVisible(false);
    setAlignmentX(Component.LEFT_ALIGNMENT);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnToggle = new javax.swing.JToggleButton();
        panelSubPreguntas = new javax.swing.JPanel();

        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        btnToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleActionPerformed(evt);
            }
        });
        add(btnToggle);

        panelSubPreguntas.setLayout(new java.awt.GridLayout());
        add(panelSubPreguntas);
    }// </editor-fold>//GEN-END:initComponents

    private void btnToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleActionPerformed
   
    panelSubPreguntas.setVisible(btnToggle.isSelected());
    revalidate();
    repaint();
    
    if (getParent() != null) {
       getParent().revalidate();
       getParent().repaint();
   }
    }//GEN-LAST:event_btnToggleActionPerformed

public ArrayList<Respuesta> getRespuestas() {
    ArrayList<Respuesta> respuestas = new ArrayList<>();

    // Iteramos sobre todos los componentes DENTRO de 'panelSubPreguntas'
    for (Component comp : panelSubPreguntas.getComponents()) {
        // Verificamos si el componente es un PreguntaPanel
        if (comp instanceof PreguntaPanel) {
            // Le pedimos su respuesta
            Respuesta r = ((PreguntaPanel) comp).getRespuesta();
            if (r != null) {
                respuestas.add(r);
            } else {
               
                return null; 
            }
        }
    }
    return respuestas;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnToggle;
    private javax.swing.JPanel panelSubPreguntas;
    // End of variables declaration//GEN-END:variables
}
