package com.mycompany.proyecto_u1;

import com.mycompany.proyecto_u1.models.Usuario;
import com.mycompany.proyecto_u1.services.EncuestaService;
import com.mycompany.proyecto_u1.models.Encuesta;
import javax.swing.JFrame;
import com.mycompany.proyecto_u1.models.Pregunta;
import javax.swing.border.EmptyBorder;
import com.mycompany.proyecto_u1.models.Respuesta;
import com.mycompany.proyecto_u1.models.RespuestaEncuesta;
import com.mycompany.proyecto_u1.services.RespuestaService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.Component;

<<<<<<< HEAD
=======


>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
public class ContestarEncuestaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContestarEncuestaFrame.class.getName());
    private Usuario usuario;
    private Encuesta encuesta;
    private VerEncuestasPanel panelPadre;
   
    public ContestarEncuestaFrame() {
    initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    setLocationRelativeTo(null);
    }
    
<<<<<<< HEAD

    public ContestarEncuestaFrame(Usuario usuario, Encuesta encuesta, VerEncuestasPanel panelPadre) {
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        initComponents(); 

        this.usuario = usuario;
        this.encuesta = encuesta;
        this.panelPadre = panelPadre;

        setTitle("Contestando: " + this.encuesta.getTitulo());

        
        com.mycompany.proyecto_u1.services.EncuestaService service = new com.mycompany.proyecto_u1.services.EncuestaService();
        java.util.ArrayList<Pregunta> preguntasDescargadas = service.getPreguntasDeEncuesta(this.encuesta.getId());
        this.encuesta.setPreguntas(preguntasDescargadas);

        generarPreguntasGUI(); 
    }


    private void generarPreguntasGUI() {

        panelContenido.removeAll();
        panelContenido.setBorder(new EmptyBorder(10, 10, 10, 10)); 

        
        for (Pregunta pregunta : this.encuesta.getPreguntas()) {

            if (pregunta.esCompleja()) {

                panelContenido.add(new ComplejaPreguntaPanel(pregunta));
            } else {

                panelContenido.add(new PreguntaPanel(pregunta));
            }
        }


        panelContenido.revalidate();
        panelContenido.repaint();
    }
=======
// AGREGAMOS EL TERCER PARÁMETRO AQUÍ: VerEncuestasPanel panelPadre
public ContestarEncuestaFrame(Usuario usuario, Encuesta encuesta, VerEncuestasPanel panelPadre) {
    // Esto evita que se cierre toda la app, solo cierra esta ventana
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    
    initComponents(); // Primero iniciamos componentes visuales
    
    this.usuario = usuario;
    this.encuesta = encuesta;
    this.panelPadre = panelPadre;

    setTitle("Contestando: " + this.encuesta.getTitulo());

    // Carga de preguntas (Código corregido anteriormente)
    com.mycompany.proyecto_u1.services.EncuestaService service = new com.mycompany.proyecto_u1.services.EncuestaService();
    java.util.ArrayList<Pregunta> preguntasDescargadas = service.getPreguntasDeEncuesta(this.encuesta.getId());
    this.encuesta.setPreguntas(preguntasDescargadas);
    
    generarPreguntasGUI(); 
}


private void generarPreguntasGUI() {
    
    panelContenido.removeAll();
    
    
    panelContenido.setBorder(new EmptyBorder(10, 10, 10, 10)); // Margen
    
    //  Recorremos las preguntas
    for (Pregunta pregunta : this.encuesta.getPreguntas()) {
        
        if (pregunta.esCompleja()) {
            
            panelContenido.add(new ComplejaPreguntaPanel(pregunta));
        } else {
            
            panelContenido.add(new PreguntaPanel(pregunta));
        }
    }
    
   
    panelContenido.revalidate();
    panelContenido.repaint();
}
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPreguntas = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        btnGuardarRespuestas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPreguntas.setBackground(new java.awt.Color(239, 242, 242));
        panelPreguntas.setLayout(new java.awt.BorderLayout());

        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));
        panelPreguntas.add(panelContenido, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(panelPreguntas);

        btnGuardarRespuestas.setBackground(new java.awt.Color(242, 255, 222));
        btnGuardarRespuestas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardarRespuestas.setForeground(new java.awt.Color(204, 0, 0));
        btnGuardarRespuestas.setText("Guardar y Finalizar Encuesta");
        btnGuardarRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRespuestasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarRespuestas)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarRespuestas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarRespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRespuestasActionPerformed
  
    if (this.encuesta.getPreguntas() == null || this.encuesta.getPreguntas().isEmpty()) {
<<<<<<< HEAD
        JOptionPane.showMessageDialog(this, "Error: No se cargaron las preguntas...", 
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
=======
        JOptionPane.showMessageDialog(this, "Error: No se cargaron las preguntas...", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2. Preparar el objeto Respuesta
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
    RespuestaEncuesta nuevaRespuesta = new RespuestaEncuesta(
        this.encuesta.getTitulo(),
        this.usuario.getNombreUsuario()
    );
<<<<<<< HEAD
   
=======
    // IMPORTANTE: Ponemos el ID para que PHP no se pierda
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
    nuevaRespuesta.setIdEncuesta(this.encuesta.getId());

    boolean todoContestado = true;

<<<<<<< HEAD
    
=======
    // 3. Recolectar respuestas de los paneles
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
    for (Component comp : panelContenido.getComponents()) {
        
        if (comp instanceof PreguntaPanel) {
            Respuesta r = ((PreguntaPanel) comp).getRespuesta();
            if (r != null) {
                nuevaRespuesta.agregarRespuesta(r);
            } else {
                todoContestado = false;
                break; 
            }
        }
        
        if (comp instanceof ComplejaPreguntaPanel) {
            ArrayList<Respuesta> respuestasComplejas = ((ComplejaPreguntaPanel) comp).getRespuestas();
            if (respuestasComplejas != null) {
                for (Respuesta r : respuestasComplejas) {
                    nuevaRespuesta.agregarRespuesta(r);
                }
            } else {
                todoContestado = false;                 
                break; 
            }
        }
    }

<<<<<<< HEAD
   
=======
    // 4. Validar que todo esté contestado
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
    if (!todoContestado) {
        JOptionPane.showMessageDialog(this, "Por favor, contesta todas las preguntas.", "Faltan respuestas", JOptionPane.WARNING_MESSAGE);
        return;
    }

<<<<<<< HEAD
   
    RespuestaService service = new RespuestaService();
    
    if (service.guardarRespuesta(nuevaRespuesta)) {
        
        JOptionPane.showMessageDialog(this, "¡Gracias! Tus respuestas han sido guardadas.");

       
        if (this.panelPadre != null) {
            System.out.println("Refrescando panel padre...");
            this.panelPadre.cargarEncuestas(); 
        }
        

        this.dispose(); 
    } else {
        // --- ERROR ---
        JOptionPane.showMessageDialog(this, "Error al guardar en la BD.", "Error", JOptionPane.ERROR_MESSAGE);
        
=======
    // 5. ENVIAR A LA BASE DE DATOS
    RespuestaService service = new RespuestaService();
    
    if (service.guardarRespuesta(nuevaRespuesta)) {
        // --- ÉXITO ---
        JOptionPane.showMessageDialog(this, "¡Gracias! Tus respuestas han sido guardadas.");

        // --- AQUÍ REFRESCAMOS AL PADRE (SOLO SI SE GUARDÓ BIEN) ---
        if (this.panelPadre != null) {
            System.out.println("Refrescando panel padre...");
            this.panelPadre.cargarEncuestas(); // <--- AQUÍ ESTABA EL ERROR (FALTABA EL PUNTO)
        }
        // ----------------------------------------------------------

        this.dispose(); // Cerramos la ventana SOLO si salió bien
        
    } else {
        // --- ERROR ---
        JOptionPane.showMessageDialog(this, "Error al guardar en la BD.", "Error", JOptionPane.ERROR_MESSAGE);
        // No cerramos la ventana (no ponemos dispose) para que el usuario intente de nuevo
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
    }    


    }//GEN-LAST:event_btnGuardarRespuestasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContestarEncuestaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarRespuestas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelPreguntas;
    // End of variables declaration//GEN-END:variables
}
