package com.mycompany.proyecto_u1;

import com.mycompany.proyecto_u1.models.Usuario;
import com.mycompany.proyecto_u1.models.Encuesta;
import javax.swing.JFrame;
import com.mycompany.proyecto_u1.models.Pregunta;
import javax.swing.border.EmptyBorder;
import com.mycompany.proyecto_u1.models.Respuesta;
import com.mycompany.proyecto_u1.models.RespuestaEncuesta;
import com.mycompany.proyecto_u1.services.RespuestaService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.Component;



public class ContestarEncuestaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContestarEncuestaFrame.class.getName());
    private Usuario usuario;
    private Encuesta encuesta;
   
    public ContestarEncuestaFrame() {
    initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    setLocationRelativeTo(null);
    }
    
    public ContestarEncuestaFrame(Usuario usuario, Encuesta encuesta) {
    this(); 
    this.usuario = usuario;
    this.encuesta = encuesta;

    setTitle("Contestando: " + this.encuesta.getTitulo());

    generarPreguntasGUI();
}


private void generarPreguntasGUI() {
    
    panelContenido.removeAll();
    
    
    panelContenido.setBorder(new EmptyBorder(10, 10, 10, 10)); // Margen
    
    //  Recorremos las preguntas
    for (Pregunta pregunta : this.encuesta.getPreguntas()) {
        
        if (pregunta.esCompleja()) {
            
            panelContenido.add(new ComplejaPreguntaPanel(pregunta));
        } else {
            
            panelContenido.add(new PreguntaPanel(pregunta));
        }
    }
    
   
    panelContenido.revalidate();
    panelContenido.repaint();
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPreguntas = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        btnGuardarRespuestas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPreguntas.setBackground(new java.awt.Color(239, 242, 242));
        panelPreguntas.setLayout(new java.awt.BorderLayout());

        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));
        panelPreguntas.add(panelContenido, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(panelPreguntas);

        btnGuardarRespuestas.setBackground(new java.awt.Color(242, 255, 222));
        btnGuardarRespuestas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardarRespuestas.setForeground(new java.awt.Color(204, 0, 0));
        btnGuardarRespuestas.setText("Guardar y Finalizar Encuesta");
        btnGuardarRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRespuestasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarRespuestas)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarRespuestas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarRespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRespuestasActionPerformed
                                               
  
    RespuestaEncuesta nuevaRespuesta = new RespuestaEncuesta(
        this.encuesta.getTitulo(),
        this.usuario.getNombreUsuario()
    );

    boolean todoContestado = true;


    for (Component comp : panelContenido.getComponents()) {
        
       
        if (comp instanceof PreguntaPanel) {
            Respuesta r = ((PreguntaPanel) comp).getRespuesta();
            if (r != null) {
                nuevaRespuesta.agregarRespuesta(r);
            } else {
                todoContestado = false; // ¡Falta una respuesta!
                break; 
            }
        }
        
        
        if (comp instanceof ComplejaPreguntaPanel) {
            
            ArrayList<Respuesta> respuestasComplejas = ((ComplejaPreguntaPanel) comp).getRespuestas();
            if (respuestasComplejas != null) {
                // Añadimos todas las sub-respuestas a nuestra respuesta principal
                for (Respuesta r : respuestasComplejas) {
                    nuevaRespuesta.agregarRespuesta(r);
                }
            } else {
                todoContestado = false;                 
                break; 
            }
        }
    }

   
    if (!todoContestado) {
        JOptionPane.showMessageDialog(this, "Por favor, contesta todas las preguntas de la encuesta.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
   
        RespuestaService service = new RespuestaService();
        
        //  Guardar en la Base de Datos
        if (service.guardarRespuesta(nuevaRespuesta)) {
            JOptionPane.showMessageDialog(this, "¡Gracias por contestar la encuesta! Tus respuestas han sido guardadas.", "Encuesta Finalizada", JOptionPane.INFORMATION_MESSAGE);
            
            
            this.dispose();
         
            if (usuario != null) {
                 
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se pudieron guardar tus respuestas en la base de datos.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
        }    

    }//GEN-LAST:event_btnGuardarRespuestasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContestarEncuestaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarRespuestas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelPreguntas;
    // End of variables declaration//GEN-END:variables
}
