
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Encuesta; 
import javax.swing.JOptionPane; 
import com.mycompany.proyecto_u1.services.EncuestaService; 
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

public class CrearEncuestaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearEncuestaFrame.class.getName());
    private AdminFrame parentFrame; 
    private String imagenSeleccionada = "";
   
    public CrearEncuestaFrame(){}
    
    public CrearEncuestaFrame(AdminFrame parent) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.parentFrame = parent;

        setTitle("Crear Nueva Encuesta");

        
        setLocationRelativeTo(null); 

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        fieldTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        btnSeleccionarImagen = new javax.swing.JButton();
        panelImagenPreview = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Encuesta");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Título de la Encuesta:");

        fieldTitulo.setBackground(new java.awt.Color(255, 255, 229));
        fieldTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Descripción (Opcional):");

        areaDescripcion.setBackground(new java.awt.Color(228, 255, 255));
        areaDescripcion.setColumns(20);
        areaDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        areaDescripcion.setRows(5);
        jScrollPane1.setViewportView(areaDescripcion);

        btnSiguiente.setBackground(new java.awt.Color(255, 255, 204));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(204, 0, 0));
        btnSiguiente.setText("Siguiente: Añadir Preguntas");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnSeleccionarImagen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarImagen.setText("Seleccionar Imagen...");
        btnSeleccionarImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagenActionPerformed(evt);
            }
        });

        panelImagenPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panelImagenPreviewLayout = new javax.swing.GroupLayout(panelImagenPreview);
        panelImagenPreview.setLayout(panelImagenPreviewLayout);
        panelImagenPreviewLayout.setHorizontalGroup(
            panelImagenPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImagenPreviewLayout.setVerticalGroup(
            panelImagenPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(panelImagenPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(panelImagenPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
    
    String titulo = fieldTitulo.getText();
    String descripcion = areaDescripcion.getText();
    
    //para vee si el titulo esta vacio, no deber ser vacio
    if (titulo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(
            this, 
            "El título de la encuesta es obligatorio.", 
            "Error de Validación", 
            JOptionPane.WARNING_MESSAGE
        );
        return; 
    }
    
    //  Crear el objeto Encuesta en memoria
    Encuesta nuevaEncuesta = new Encuesta(titulo, descripcion);
    nuevaEncuesta.setImagen(this.imagenSeleccionada);

    
    
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           new PreguntasFrame(CrearEncuestaFrame.this, nuevaEncuesta).setVisible(true);
        }
    });

   
    this.dispose();
    
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
      if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser.getSelectedFile();
        String fileName = file.getName();

        // Validar que sea una imagen
        if (fileName.endsWith(".png") || fileName.endsWith(".jpg") || fileName.endsWith(".jpeg")) {
            // Copiar la imagen al proyecto
            if (!copiarArchivo(file.toPath(), fileName)) return;

            
            panelImagenPreview.setIcon(
                new javax.swing.ImageIcon(EncuestaService.IMG_PATH + fileName)
            );
            panelImagenPreview.updateUI();

            // Guardar el nombre del archivo
            this.imagenSeleccionada = fileName;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una imagen (png, jpg, jpeg).");
        }
    }
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearEncuestaFrame().setVisible(true));
    }
    
    private boolean copiarArchivo(Path original, String copiado) {
    boolean result = false;
    try {
        Path path = Paths.get(EncuestaService.IMG_PATH + copiado);
        Files.copy(original, path, StandardCopyOption.REPLACE_EXISTING);
        result = true;
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al copiar la imagen: " + e.getMessage());
    }
    return result;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField fieldTitulo;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.PanelImage panelImagenPreview;
    // End of variables declaration//GEN-END:variables
}
