
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Encuesta;
import com.mycompany.proyecto_u1.models.Usuario;
import com.mycompany.proyecto_u1.services.EncuestaService;
 import java.net.URL;
 import javax.imageio.ImageIO;
 import java.awt.Image;

    public class EncuestaCardPanel extends javax.swing.JPanel {
        private Encuesta encuesta;
        private Usuario usuario;
        private UsuarioFrame parentFrame;
        private VerEncuestasPanel panelPadre;


    public EncuestaCardPanel(UsuarioFrame parentFrame, Usuario usuario, Encuesta encuesta, VerEncuestasPanel panelPadre) {
        initComponents();
        this.parentFrame = parentFrame;
        this.usuario = usuario;
        this.encuesta = encuesta;this.panelPadre = panelPadre;

        labelTitulo.setText(encuesta.getTitulo());
        areaDescripcionCard.setText(encuesta.getDescripcion());

    
        try {
            String nombreImagen = encuesta.getImagen();
            if (nombreImagen == null || nombreImagen.isEmpty()) {
                nombreImagen = "no_image_2.jpg"; 
            }


            String urlFoto = "http://localhost/PROYECTO_U1/imagenes/" + nombreImagen;
            URL url = new URL(urlFoto);
            Image imagenWeb = ImageIO.read(url);

            if (imagenWeb != null) {

                Image imgEscalada = imagenWeb.getScaledInstance(190, 150, Image.SCALE_SMOOTH);
                panelImagen.setIcon(new javax.swing.ImageIcon(imgEscalada));
                panelImagen.repaint();
            }
        } catch (Exception e) {
            System.out.println("No se pudo cargar imagen de encuesta: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new org.edisoncor.gui.panel.PanelImage();
        labelTitulo = new javax.swing.JLabel();
        btnContestar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcionCard = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(360, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImagen.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 190, 150));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 340, 20));

        btnContestar.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        btnContestar.setText("Contestar Encuesta");
        btnContestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContestarActionPerformed(evt);
            }
        });
        add(btnContestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 180, 30));

        areaDescripcionCard.setEditable(false);
        areaDescripcionCard.setColumns(20);
        areaDescripcionCard.setLineWrap(true);
        areaDescripcionCard.setRows(5);
        areaDescripcionCard.setWrapStyleWord(true);
        areaDescripcionCard.setBorder(null);
        areaDescripcionCard.setOpaque(false);
        jScrollPane1.setViewportView(areaDescripcionCard);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 340, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContestarActionPerformed
    ContestarEncuestaFrame frame = new ContestarEncuestaFrame(usuario, encuesta, this.panelPadre);
    frame.setVisible(true);
    }//GEN-LAST:event_btnContestarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcionCard;
    private javax.swing.JButton btnContestar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private org.edisoncor.gui.panel.PanelImage panelImagen;
    // End of variables declaration//GEN-END:variables
}
