
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Encuesta;
import com.mycompany.proyecto_u1.models.Usuario;
import com.mycompany.proyecto_u1.services.EncuestaService;
public class EncuestaCardPanel extends javax.swing.JPanel {
    private Encuesta encuesta;
    private Usuario usuario;
    private UsuarioFrame parentFrame;


    
    public EncuestaCardPanel(UsuarioFrame parentFrame, Usuario usuario, Encuesta encuesta) {
    initComponents();
    this.parentFrame = parentFrame;
    this.usuario = usuario;
    this.encuesta = encuesta;

   
    labelTitulo.setText(encuesta.getTitulo());
    
    areaDescripcionCard.setText(encuesta.getDescripcion());

    
    String img = EncuestaService.IMG_PATH + "no_image_2.jpg"; 
    if (encuesta.getImagen() != null && !encuesta.getImagen().isEmpty()) {
        img = EncuestaService.IMG_PATH + encuesta.getImagen();
    }
    panelImagen.setIcon(new javax.swing.ImageIcon(img));
    panelImagen.updateUI();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new org.edisoncor.gui.panel.PanelImage();
        labelTitulo = new javax.swing.JLabel();
        btnContestar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcionCard = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(360, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImagen.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 190, 150));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 340, 20));

        btnContestar.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        btnContestar.setText("Contestar Encuesta");
        btnContestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContestarActionPerformed(evt);
            }
        });
        add(btnContestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 180, 30));

        areaDescripcionCard.setEditable(false);
        areaDescripcionCard.setColumns(20);
        areaDescripcionCard.setLineWrap(true);
        areaDescripcionCard.setRows(5);
        areaDescripcionCard.setWrapStyleWord(true);
        areaDescripcionCard.setBorder(null);
        areaDescripcionCard.setOpaque(false);
        jScrollPane1.setViewportView(areaDescripcionCard);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 340, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContestarActionPerformed
        // Abrir la nueva ventana para contestar
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ContestarEncuestaFrame(usuario, encuesta).setVisible(true);
        }
    });

    // Cerrar la ventana principal de Usuario
    this.parentFrame.dispose();
    }//GEN-LAST:event_btnContestarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcionCard;
    private javax.swing.JButton btnContestar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private org.edisoncor.gui.panel.PanelImage panelImagen;
    // End of variables declaration//GEN-END:variables
}
