
package com.mycompany.proyecto_u1;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.border.EmptyBorder;

public class GraficaBarraPanel extends javax.swing.JPanel {
private String textoPregunta;
private int[] conteos; 
private int maxConteo = 0;
private static final Color[] COLORES_BARRAS = {
    new Color(255, 102, 102), // 1-Totalmente en Desacuerdo
    new Color(255, 178, 102), // 2-En Desacuerdo
    new Color(255, 255, 102), // 3-Neutral
    new Color(178, 255, 102), // 4-De Acuerdo
    new Color(102, 255, 102)  // 5-Totalmente de Acuerdo
};

public GraficaBarraPanel(String textoPregunta, int[] conteos) {
    initComponents();
    this.textoPregunta = textoPregunta;
    this.conteos = conteos;

    // Poner un margen
    setBorder(new EmptyBorder(10, 10, 10, 10));

<<<<<<< HEAD
     
=======
    // Calcular el voto más alto 
>>>>>>> 49e4d57e077d868eb4b56f7a49fea803254f625c
    for (int conteo : conteos) {
        if (conteo > maxConteo) {
            maxConteo = conteo;
        }
    }

    // Damos un tamaño  para el JScrollPane 
    setPreferredSize(new java.awt.Dimension(400, 180));
}

@Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);

    int panelWidth = getWidth();
    int panelHeight = getHeight();
    
    
    int topMargin = 50;     
    int bottomMargin = 30;  
    

    int barWidth = (panelWidth - 60) / 5; 
    int startX = 40; 

    
    g.setColor(Color.BLACK);
    g.setFont(new Font("Segoe UI", Font.BOLD, 14));
    g.drawString(textoPregunta, startX, 30); 

    if (maxConteo == 0) {
        g.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        g.drawString("Nadie ha respondido esta pregunta aún.", startX, 60);
        return; 
    }

   
    int maxBarPixelHeight = panelHeight - topMargin - bottomMargin; 

  
    for (int i = 0; i < conteos.length; i++) {
      
        int barHeight = 0;
        if (maxConteo > 0) { 
            barHeight = (int) (((double) conteos[i] / maxConteo) * maxBarPixelHeight); 
        }

       
        int y = panelHeight - barHeight - bottomMargin; 

       
        g.setColor(COLORES_BARRAS[i]);
        g.fillRect(startX, y, barWidth - 10, barHeight); 

    
        g.setColor(Color.blue);
        g.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        String etiqueta = (i + 1) + "";
        String conteoStr = conteos[i] + " votos";
   
        int yConteo = Math.max(topMargin, y - 5);
        
      
        int yFlotante = y - 5;
        if (yFlotante < 45) yFlotante = 45; 
        g.drawString(conteoStr, startX + (barWidth / 2) - 20, yFlotante);
        

        g.drawString(etiqueta, startX + (barWidth / 2) - 10, panelHeight - 15);

        startX += barWidth; 
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
