
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Pregunta;
import java.awt.Component;
import java.util.Enumeration; 
import javax.swing.AbstractButton;
import com.mycompany.proyecto_u1.models.Respuesta;

public class PreguntaPanel extends javax.swing.JPanel {
    private Pregunta pregunta;
    
    public PreguntaPanel() {
        initComponents();
    grupoLikert.add(radio1);
    grupoLikert.add(radio2);
    grupoLikert.add(radio3);
    grupoLikert.add(radio4);
    grupoLikert.add(radio5);
    }
    
    public PreguntaPanel(Pregunta pregunta) {
    initComponents();
    
    grupoLikert.add(radio1);
    grupoLikert.add(radio2);
    grupoLikert.add(radio3);
    grupoLikert.add(radio4);
    grupoLikert.add(radio5);

    // Guardamos la pregunta y ponemos el texto
    this.pregunta = pregunta;
    labelPregunta.setText(pregunta.getTexto());

    // Guardamos la "puntuación" (1-5) en cada botón para usarla después
    radio1.putClientProperty("puntuacion", 1);
    radio2.putClientProperty("puntuacion", 2);
    radio3.putClientProperty("puntuacion", 3);
    radio4.putClientProperty("puntuacion", 4);
    radio5.putClientProperty("puntuacion", 5);
    
    setAlignmentX(Component.LEFT_ALIGNMENT);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoLikert = new javax.swing.ButtonGroup();
        labelPregunta = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio5 = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPregunta.setText("jLabel1");
        add(labelPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, -1));

        radio1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        radio1.setForeground(new java.awt.Color(204, 0, 0));
        radio1.setText("1 - Totalmente en Desacuerdo");
        add(radio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        radio2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        radio2.setForeground(new java.awt.Color(204, 153, 0));
        radio2.setText("2 - En Desacuerdo");
        add(radio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        radio3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        radio3.setForeground(new java.awt.Color(153, 0, 153));
        radio3.setText("3 - Neutral");
        add(radio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        radio4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        radio4.setForeground(new java.awt.Color(0, 153, 153));
        radio4.setText("4 - De Acuerdo");
        add(radio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        radio5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        radio5.setForeground(new java.awt.Color(51, 51, 255));
        radio5.setText("5 - Totalmente de Acuerdo");
        radio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5ActionPerformed(evt);
            }
        });
        add(radio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
  
public Respuesta getRespuesta() {
    
    for (Enumeration<AbstractButton> buttons = grupoLikert.getElements(); buttons.hasMoreElements();) {
        AbstractButton button = buttons.nextElement();

        if (button.isSelected()) {
            
            int puntuacion = (int) button.getClientProperty("puntuacion");
            
           return new Respuesta(this.pregunta.getId(), this.pregunta.getTexto(), puntuacion);
        }
    }
    return null; 
}
    private void radio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5ActionPerformed
        
    }//GEN-LAST:event_radio5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoLikert;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    // End of variables declaration//GEN-END:variables



}
