package com.mycompany.proyecto_u1;

import com.mycompany.proyecto_u1.models.Encuesta;
import com.mycompany.proyecto_u1.models.Pregunta;
import com.mycompany.proyecto_u1.services.EncuestaService;
import javax.swing.DefaultListModel; 
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.ArrayList;

public class PreguntasFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PreguntasFrame.class.getName());
     private CrearEncuestaFrame parentFrame; 
    private Encuesta encuesta;
    
    public PreguntasFrame() {
         initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Añadir Preguntas");
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
  public PreguntasFrame(CrearEncuestaFrame parent, Encuesta encuesta) {
        this(); 
        
        this.parentFrame = parent;
        this.encuesta = encuesta;

        setTitle("Añadir Preguntas a: " + this.encuesta.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldNuevaPregunta = new javax.swing.JTextField();
        btnAgregarSimple = new javax.swing.JButton();
        btnAgregarCompleja = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPreguntas = new javax.swing.JList<>();
        btnFinalizarEncuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Texto de la Nueva Pregunta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 55, -1, -1));

        fieldNuevaPregunta.setBackground(new java.awt.Color(255, 245, 248));
        fieldNuevaPregunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(fieldNuevaPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 56, 580, -1));

        btnAgregarSimple.setBackground(new java.awt.Color(204, 255, 204));
        btnAgregarSimple.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarSimple.setText("Añadir Pregunta Simple");
        btnAgregarSimple.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        btnAgregarSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSimpleActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 200, 39));

        btnAgregarCompleja.setBackground(new java.awt.Color(255, 255, 204));
        btnAgregarCompleja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarCompleja.setText("Añadir Pregunta Compleja");
        btnAgregarCompleja.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        btnAgregarCompleja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComplejaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCompleja, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 200, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Preguntas de la Encuesta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 165, -1, -1));

        listPreguntas.setBackground(new java.awt.Color(236, 248, 255));
        listPreguntas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listPreguntas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1160, 340));

        btnFinalizarEncuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnFinalizarEncuesta.setForeground(new java.awt.Color(255, 0, 0));
        btnFinalizarEncuesta.setText("Finalizar y Guardar Encuesta");
        btnFinalizarEncuesta.setBorder(new javax.swing.border.MatteBorder(null));
        btnFinalizarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarEncuestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarEncuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSimpleActionPerformed
      String textoPregunta = fieldNuevaPregunta.getText();

        if (textoPregunta.trim().length() < 3) {
            JOptionPane.showMessageDialog(
                this, 
                "El texto de la pregunta debe tener al menos 3 caracteres.", 
                "Error", 
                JOptionPane.WARNING_MESSAGE
            );
            return; 
        }
        Pregunta nuevaPregunta = new Pregunta(textoPregunta);

        this.encuesta.agregarPregunta(nuevaPregunta);

        fieldNuevaPregunta.setText("");

        actualizarListaPreguntas();
    }//GEN-LAST:event_btnAgregarSimpleActionPerformed

    private void btnAgregarComplejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComplejaActionPerformed
         // Validar el texto de la "pregunta madre"
        String textoPreguntaMadre = fieldNuevaPregunta.getText();
        if (textoPreguntaMadre.trim().length() < 3) {
            JOptionPane.showMessageDialog(this, "El texto de la pregunta compleja debe tener al menos 3 caracteres.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Pregunta preguntaMadre = new Pregunta(textoPreguntaMadre);

        SubPreguntasDialog dialog = new SubPreguntasDialog(this, true, preguntaMadre);
        dialog.setVisible(true);

        if (preguntaMadre.esCompleja()) {
            this.encuesta.agregarPregunta(preguntaMadre);
            
            fieldNuevaPregunta.setText("");
            
            actualizarListaPreguntas();
        }
    }//GEN-LAST:event_btnAgregarComplejaActionPerformed

    private void btnFinalizarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarEncuestaActionPerformed
   // Validar que la encuesta tenga al menos una pregunta
        if (this.encuesta.getPreguntas().isEmpty()) {
            JOptionPane.showMessageDialog(
                this, 
                "La encuesta debe tener al menos una pregunta para poder guardarla.", 
                "Error", 
                JOptionPane.WARNING_MESSAGE
            );
            return; 
        }

        
        EncuestaService service = new EncuestaService();

        
        if (service.crearEncuesta(this.encuesta)) {
            JOptionPane.showMessageDialog(
                this, 
                "¡Encuesta guardada con éxito en la Base de Datos!", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE
            );
            
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(
                this, 
                "Error: No se pudo guardar la encuesta en la base de datos.", 
                "Error de Guardado", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnFinalizarEncuestaActionPerformed

   
private void actualizarListaPreguntas() {
        DefaultListModel<String> modelo = new DefaultListModel<>();

        for (Pregunta p : this.encuesta.getPreguntas()) {
            if (p.esCompleja()) {
                modelo.addElement("[COMPLEJA] " + p.getTexto());
            } else {
                modelo.addElement(p.getTexto());
            }
        }

        listPreguntas.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PreguntasFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCompleja;
    private javax.swing.JButton btnAgregarSimple;
    private javax.swing.JButton btnFinalizarEncuesta;
    private javax.swing.JTextField fieldNuevaPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPreguntas;
    // End of variables declaration//GEN-END:variables
}
