
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Pregunta;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class SubPreguntasDialog extends java.awt.Dialog {
    private Pregunta preguntaMadre;
    
    
public SubPreguntasDialog(java.awt.Frame parent, boolean modal, Pregunta preguntaMadre) {
    super(parent, modal); 
    initComponents();     

    
    this.preguntaMadre = preguntaMadre; 
    setTitle("Añadiendo sub-preguntas a: " + this.preguntaMadre.getTexto());
    setLocationRelativeTo(parent);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fieldNuevaSubPregunta = new javax.swing.JTextField();
        btnAnadirSub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSubPreguntas = new javax.swing.JList<>();
        btnFinalizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setTitle("Pregunta Compleja");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Texto de la Sub-Pregunta:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        fieldNuevaSubPregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(fieldNuevaSubPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 590, 30));

        btnAnadirSub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAnadirSub.setText("Añadir Sub-Pregunta");
        btnAnadirSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAnadirSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirSubActionPerformed(evt);
            }
        });
        add(btnAnadirSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 140, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Sub-Preguntas Añadidas:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        listSubPreguntas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listSubPreguntas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 910, 180));

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 0, 0));
        btnFinalizar.setText("Finalizar Pregunta Compleja");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 270, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnAnadirSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirSubActionPerformed
      String textoSubPregunta = fieldNuevaSubPregunta.getText();

    
    if (textoSubPregunta.trim().length() < 3) {
        JOptionPane.showMessageDialog(this, "La sub-pregunta debe tener al menos 3 caracteres.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    Pregunta subPregunta = new Pregunta(textoSubPregunta);

    
    this.preguntaMadre.agregarSubPregunta(subPregunta);

    
    fieldNuevaSubPregunta.setText("");

    
    actualizarListaSubPreguntas();
    }//GEN-LAST:event_btnAnadirSubActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
    // Validar que al menos se haya añadido una sub-pregunta
    if (!this.preguntaMadre.esCompleja()) {
         JOptionPane.showMessageDialog(this, "Debe añadir al menos una sub-pregunta para guardarla como 'Compleja'.", "Error", JOptionPane.WARNING_MESSAGE);
         return;
    }

    
    this.dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed
    private void actualizarListaSubPreguntas() {
    DefaultListModel<String> modelo = new DefaultListModel<>();
    // Recorremos las sub-preguntas de nuestra pregunta madre
    for (Pregunta sub : this.preguntaMadre.getSubPreguntas()) {
        modelo.addElement(sub.getTexto());
    }
    listSubPreguntas.setModel(modelo);
}
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirSub;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JTextField fieldNuevaSubPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listSubPreguntas;
    // End of variables declaration//GEN-END:variables
}
