
package com.mycompany.proyecto_u1;
import com.mycompany.proyecto_u1.models.Usuario;
//import com.mycompany.proyecto_u1.services.UsuarioService;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class UsuarioFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsuarioFrame.class.getName());
    private Usuario usuario;
    
    public UsuarioFrame(){}  

   public UsuarioFrame(Usuario usuario) {
   initComponents();
    this.usuario = usuario;
    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setTitle("Encuestas - Bienvenido, " + this.usuario.getNombreUsuario());
  
    BienvenidaPanel panelBienvenida = new BienvenidaPanel(this.usuario);


    mostrarPanel(panelBienvenida);
    
    
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuVerDisponibles = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuVerContestadas = new javax.swing.JMenuItem();
        menuCerrarSesionUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setLayout(new java.awt.CardLayout());

        jMenu1.setText("Encuestas");

        menuVerDisponibles.setText("Ver Encuestas Disponibles");
        menuVerDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerDisponiblesActionPerformed(evt);
            }
        });
        jMenu1.add(menuVerDisponibles);
        jMenu1.add(jSeparator1);

        menuVerContestadas.setText("Ver Mis Encuestas Contestadas");
        menuVerContestadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerContestadasActionPerformed(evt);
            }
        });
        jMenu1.add(menuVerContestadas);

        jMenuBar1.add(jMenu1);

        menuCerrarSesionUsuario.setText("Archivo");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCerrarSesionUsuario.add(jMenuItem1);

        jMenuBar1.add(menuCerrarSesionUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVerDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerDisponiblesActionPerformed
    VerEncuestasPanel panelEncuestas = new VerEncuestasPanel(this, this.usuario);
    
    contentPanel.removeAll();
    contentPanel.add(panelEncuestas);
    contentPanel.revalidate();
    contentPanel.repaint();
    }//GEN-LAST:event_menuVerDisponiblesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     int confirm = JOptionPane.showConfirmDialog(
        this, 
        "¿Estás seguro de que quieres cerrar sesión?", 
        "Cerrar Sesión", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose(); 

        // Abre una nueva ventana de Login
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new com.mycompany.proyecto_u1.LoginFrame().setVisible(true);
            }
        });
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuVerContestadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerContestadasActionPerformed
     
    AcusePanel panelAcuses = new AcusePanel(this.usuario);

    
    contentPanel.removeAll();
    contentPanel.add(panelAcuses);
    contentPanel.revalidate();
    contentPanel.repaint();
    }//GEN-LAST:event_menuVerContestadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsuarioFrame().setVisible(true));
    }
public void mostrarPanel(JPanel panel) {
    contentPanel.removeAll();
    contentPanel.add(panel);
    contentPanel.revalidate();
    contentPanel.repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuCerrarSesionUsuario;
    private javax.swing.JMenuItem menuVerContestadas;
    private javax.swing.JMenuItem menuVerDisponibles;
    // End of variables declaration//GEN-END:variables
public Usuario getUsuario() {
    return this.usuario;
}

}
