package com.mycompany.proyecto_u1;

import com.mycompany.proyecto_u1.models.Encuesta;
import com.mycompany.proyecto_u1.services.EncuestaService;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import com.mycompany.proyecto_u1.services.ReporteService;
import javax.swing.JFileChooser; 
import java.io.File;

public class VerResultadosPanel extends javax.swing.JPanel {
    private AdminFrame parentFrame;
   
 public VerResultadosPanel(AdminFrame parent) {
    initComponents();
    this.parentFrame = parent; 
    cargarEncuestas();
}
    
    
   private void cargarEncuestas() {
        
        EncuestaService service = new EncuestaService();
        
       
        ArrayList<Encuesta> encuestas = service.getEncuestas();
        
        DefaultListModel<Encuesta> modelo = new DefaultListModel<>();
        for (Encuesta e : encuestas) {
            modelo.addElement(e);
        }

        listEncuestas.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEncuestas = new javax.swing.JList<>();
        btnPublicar = new javax.swing.JButton();
        btnVerGrafica = new javax.swing.JButton();
        btnDescargarExcel = new javax.swing.JButton();
        btnDescargarPDF = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        btnBorrar = new javax.swing.JButton();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Encuestas Guardadas:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        listEncuestas.setBackground(new java.awt.Color(227, 255, 250));
        listEncuestas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listEncuestas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1200, 360));

        btnPublicar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPublicar.setText("Publicar Encuesta Seleccionada");
        btnPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarActionPerformed(evt);
            }
        });
        add(btnPublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 230, 30));

        btnVerGrafica.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnVerGrafica.setText("Ver Gráfica de Resultados");
        btnVerGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGraficaActionPerformed(evt);
            }
        });
        add(btnVerGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 240, 30));

        btnDescargarExcel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDescargarExcel.setText("Descargar Excel");
        btnDescargarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarExcelActionPerformed(evt);
            }
        });
        add(btnDescargarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 200, 30));

        btnDescargarPDF.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDescargarPDF.setText("Descargar PDF");
        btnDescargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarPDFActionPerformed(evt);
            }
        });
        add(btnDescargarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, 190, 30));

        panelImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\blanc\\OneDrive\\Documentos\\NetBeansProjects\\PROYECTO_U1\\src\\main\\java\\com\\mycompany\\proyecto_u1\\images\\iconPublicar.png")); // NOI18N
        add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 150, 130));

        panelImage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\blanc\\OneDrive\\Documentos\\NetBeansProjects\\PROYECTO_U1\\src\\main\\java\\com\\mycompany\\proyecto_u1\\images\\iconGrafica.png")); // NOI18N
        add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 130, 130));

        panelImage3.setIcon(new javax.swing.ImageIcon("C:\\Users\\blanc\\OneDrive\\Documentos\\NetBeansProjects\\PROYECTO_U1\\src\\main\\java\\com\\mycompany\\proyecto_u1\\images\\iconExcel.png")); // NOI18N
        add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 120, 130));

        panelImage4.setIcon(new javax.swing.ImageIcon("C:\\Users\\blanc\\OneDrive\\Documentos\\NetBeansProjects\\PROYECTO_U1\\src\\main\\java\\com\\mycompany\\proyecto_u1\\images\\iconPDF.png")); // NOI18N
        add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 460, 120, 120));

        btnBorrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBorrar.setText("Borrar Encuesta");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 190, 30));

        panelImage5.setIcon(new javax.swing.ImageIcon("C:\\Users\\blanc\\OneDrive\\Documentos\\NetBeansProjects\\PROYECTO_U1\\images\\borrar.jpg")); // NOI18N
        add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 140, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarActionPerformed
    
        Encuesta encuestaSeleccionada = listEncuestas.getSelectedValue();

        
        if (encuestaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una encuesta de la lista.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
        if (encuestaSeleccionada.isEstaPublicada()) {
            JOptionPane.showMessageDialog(this, "Esta encuesta ya ha sido publicada.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de publicar la encuesta '" + encuestaSeleccionada.getTitulo() + "'?\nUna vez publicada, los usuarios podrán verla.",
            "Confirmar Publicación",
            JOptionPane.YES_NO_OPTION
        );
        
                if (confirm == JOptionPane.YES_OPTION) {
           
            EncuestaService service = new EncuestaService();
            
            if (service.publicarEncuesta(encuestaSeleccionada.getTitulo())) {
                JOptionPane.showMessageDialog(this, "¡Encuesta publicada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarEncuestas(); // Recargar la lista para ver el cambio (si usas algún indicador visual)
            } else {
                JOptionPane.showMessageDialog(this, "Error al publicar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPublicarActionPerformed

    private void btnVerGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGraficaActionPerformed
                                                 
    
    Encuesta encuestaSeleccionada = listEncuestas.getSelectedValue();

   
    if (encuestaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una encuesta de la lista.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    AdminFrame framePadre = this.parentFrame;
   
    GraficasPanel panelGraficas = new GraficasPanel(framePadre, encuestaSeleccionada);

    
    framePadre.mostrarPanel(panelGraficas);

    }//GEN-LAST:event_btnVerGraficaActionPerformed

    private void btnDescargarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarExcelActionPerformed
    
   
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte General de Excel");
    
    
    fileChooser.setSelectedFile(new File("Reporte_General_Encuestas.xlsx"));

    int userSelection = fileChooser.showSaveDialog(this.parentFrame);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File archivoParaGuardar = fileChooser.getSelectedFile();
        
        
        if (!archivoParaGuardar.getName().toLowerCase().endsWith(".xlsx")) {
            archivoParaGuardar = new File(archivoParaGuardar.getParentFile(), archivoParaGuardar.getName() + ".xlsx");
        }

        
        boolean exito = ReporteService.generarExcelReporteGeneral(archivoParaGuardar);

        if (exito) {
            JOptionPane.showMessageDialog(this.parentFrame, "¡Reporte general de Excel guardado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this.parentFrame, "Error: No se pudo guardar el reporte general.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDescargarExcelActionPerformed

    private void btnDescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarPDFActionPerformed
        // Obtener la encuesta seleccionada
    Encuesta encuestaSeleccionada = listEncuestas.getSelectedValue();
    if (encuestaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una encuesta para exportar.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Abrir el diálogo "Guardar Como..."
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte en PDF");
    // Poner nombre por defecto
    fileChooser.setSelectedFile(new File(encuestaSeleccionada.getTitulo() + ".pdf"));

    int userSelection = fileChooser.showSaveDialog(this.parentFrame);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File archivoParaGuardar = fileChooser.getSelectedFile();
        
        // Asegurarse de que termine en .pdf
        if (!archivoParaGuardar.getName().toLowerCase().endsWith(".pdf")) {
            archivoParaGuardar = new File(archivoParaGuardar.getParentFile(), archivoParaGuardar.getName() + ".pdf");
        }

        // Llamar al servicio para generar el PDF
        boolean exito = ReporteService.generarPDFEncuesta(encuestaSeleccionada, archivoParaGuardar);

        if (exito) {
            JOptionPane.showMessageDialog(this.parentFrame, "¡Reporte PDF guardado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this.parentFrame, "Error: No se pudo guardar el reporte PDF.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDescargarPDFActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
      // Obtener la encuesta seleccionada
        Encuesta encuestaSeleccionada = listEncuestas.getSelectedValue();
        if (encuestaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una encuesta de la lista para borrar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar con el admin
        int confirm = JOptionPane.showConfirmDialog(
            this.parentFrame, 
            "¿Estás seguro de borrar la encuesta '" + encuestaSeleccionada.getTitulo() + "'?\nTodas sus respuestas también serán borradas. Esta acción no se puede deshacer.",
            "Confirmar Borrado",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
           
            EncuestaService service = new EncuestaService();
            
            if (service.borrarEncuesta(encuestaSeleccionada.getTitulo())) {
                JOptionPane.showMessageDialog(this.parentFrame, "Encuesta borrada con éxito.");
                cargarEncuestas(); 
            } else {
                JOptionPane.showMessageDialog(this.parentFrame, "Error al borrar la encuesta de la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnDescargarExcel;
    private javax.swing.JButton btnDescargarPDF;
    private javax.swing.JButton btnPublicar;
    private javax.swing.JButton btnVerGrafica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Encuesta> listEncuestas;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    // End of variables declaration//GEN-END:variables
}
